name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get -y install \
            devscripts \
            debhelper \
            build-essential \
            cmake \
            libwxgtk3.0-gtk3-dev

      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Coverage ..
          make
          sudo make install

      - name: Test the 'Debian' packaging
        run: |
          debuild -us -uc
